<a href="https://colab.research.google.com/github/apichaia/PythonDataViz2026/blob/main/Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###HW6

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [92]:
import pandas as pd

In [93]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [94]:
import os

path = '/content/drive/My Drive/dataviz_2026_data'

In [95]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')
print(covid_file_path)

/content/drive/My Drive/dataviz_2026_data/confirmed-cases.csv

In [96]:
a = path + 'confirmed-cases.csv'
print(a)

/content/drive/My Drive/dataviz_2026_dataconfirmed-cases.csv

## load data to memory

In [97]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_1199/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [98]:
data_covid.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

In [99]:
data_covid.shape

(356612, 11)

## ชี้ค่าในตาราง

#### basic

In [100]:
data_covid['province_of_onset']

0         เชียงใหม่
1         เชียงใหม่
2         เชียงใหม่
3               NaN
4         เชียงใหม่
            ...
356607          NaN
356608          NaN
356609          NaN
356610          NaN
356611          NaN
Name: province_of_onset, Length: 356612, dtype: object

In [101]:
data_covid['province_of_onset'][4]

'เชียงใหม่'

#### .iloc

In [102]:
data_covid.iloc[4,7]

'เชียงใหม่'

In [103]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

# Convert 'age' column to numeric, coercing non-numeric values to NaN
female_KK_age_numeric = pd.to_numeric(female_KK['age'], errors='coerce')

sum_ages = 0
count_ages = 0
for a in female_KK_age_numeric:
    # Check if the age is not NaN and is greater than 0
    if pd.notna(a) and a > 0:
        sum_ages += a
        count_ages += 1

if count_ages > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum_ages/count_ages}')
else:
    print('ไม่พบข้อมูลอายุที่ถูกต้องสำหรับผู้ป่วยหญิงในจังหวัดขอนแก่น')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 40.67317497823654

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [104]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']]
smaller_table

       announce_date province_of_onset                  risk
0          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
1          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
2          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
3          12/4/2022               NaN  อยู่ระหว่างการสอบสวน
4          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
...              ...               ...                   ...
356607      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356608      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356609      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356610      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356611      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ

[356612 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [105]:
data_covid.iloc[1:5,:]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

In [106]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
3345,3909218,12/4/2022,11/4/2022,หญิง,27.0,ปี,Thailand,พระนครศรีอยุธยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,บ้านไผ่
3763,3909636,12/4/2022,11/4/2022,หญิง,47.0,ปี,Thailand,ปทุมธานี,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ขอนแก่น,บ้านไผ่
3823,3909696,12/4/2022,11/4/2022,ชาย,53.0,ปี,Thailand,สระบุรี,ระบุไม่ได้,ขอนแก่น,น้ำพอง
8436,3914309,12/4/2022,11/4/2022,หญิง,35.0,ปี,Thailand,ระยอง,อยู่ระหว่างการสอบสวน,ขอนแก่น,มัญจาคีรี
10537,3916410,12/4/2022,11/4/2022,หญิง,32.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,อุบลรัตน์
...,...,...,...,...,...,...,...,...,...,...,...
350028,4255901,1/5/2022,30/4/2022,หญิง,24.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เวียงเก่า
350029,4255902,1/5/2022,30/4/2022,หญิง,38.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เมืองขอนแก่น
350030,4255903,1/5/2022,30/4/2022,หญิง,27.0,ปี,Thailand,ขอนแก่น,อื่นๆ,ขอนแก่น,เมืองขอนแก่น
353787,4259660,1/5/2022,30/4/2022,NaN,26.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,ขอนแก่น,อุบลรัตน์
353880,4259753,1/5/2022,30/4/2022,NaN,30.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,ขอนแก่น,พล

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [107]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
5,3905878,12/4/2022,11/4/2022,หญิง,12.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่แตง
6,3905879,12/4/2022,11/4/2022,ชาย,32.0,ปี,Thailand,เชียงใหม่,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เชียงใหม่,แม่ริม
7,3905880,12/4/2022,11/4/2022,หญิง,55.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,สารภี

In [108]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
5,3905878,12/4/2022,11/4/2022,หญิง,12.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่แตง

In [109]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: province_of_onset, dtype: bool

In [110]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

In [111]:
this_data = data_covid[['sex','age','province_of_onset']]

In [112]:
this_data

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [113]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0         54.0
1         36.0
2         31.0
4         33.0
5         12.0
          ...
356592    27.0
356595    35.0
356597     NaN
356609     NaN
356610     NaN
Name: age, Length: 203340, dtype: object

In [114]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

In [115]:
female_KK_age_numeric = pd.to_numeric(female_KK['age'], errors='coerce')
mean_age_kk = female_KK_age_numeric.dropna().mean()

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {mean_age_kk}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 40.67317497823654

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [116]:
this_data.shape #(12423, 3)

(356612, 3)

In [117]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(356612, 11)
(262536, 11)

In [118]:
this_data.dropna().shape

(290263, 3)

In [119]:
this_data.dropna()

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
4       หญิง  33.0         เชียงใหม่
5       หญิง  12.0         เชียงใหม่
...      ...   ...               ...
356591   ชาย   7.0     กรุงเทพมหานคร
356592  หญิง  27.0     กรุงเทพมหานคร
356593   ชาย  69.0     กรุงเทพมหานคร
356594   ชาย  19.0     กรุงเทพมหานคร
356595  หญิง  35.0     กรุงเทพมหานคร

[290263 rows x 3 columns]

In [120]:
this_data.dropna()
print(this_data.shape)

(356612, 3)

In [121]:
this_data.dropna(inplace=True)

/tmp/ipykernel_1199/3935554116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [122]:
this_data.dropna(inplace=True)
print(this_data.shape)

(290263, 3)

/tmp/ipykernel_1199/2129530393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [123]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(356612, 3)

In [124]:
this_data.dropna().shape

(290263, 3)

In [125]:
this_data.dropna(subset=['age']).shape

(325395, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [126]:
this_data = data_covid[['sex','age','province_of_onset']]

In [127]:
this_data.head()

    sex   age province_of_onset
0  หญิง  54.0         เชียงใหม่
1  หญิง  36.0         เชียงใหม่
2  หญิง  31.0         เชียงใหม่
3   ชาย  37.0               NaN
4  หญิง  33.0         เชียงใหม่

In [128]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 356612
จำนวน record หลัง drop missing ใน province 321770

In [129]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  54.0         เชียงใหม่
1  หญิง  36.0         เชียงใหม่
2  หญิง  31.0         เชียงใหม่
3   ชาย  37.0            ไม่รู้
4  หญิง  33.0         เชียงใหม่

In [130]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

           sex   age province_of_onset
704     ไม่รู้    -1             ลำปาง
705     ไม่รู้    -1             ลำปาง
706     ไม่รู้    -1             ลำปาง
707     ไม่รู้    -1             ลำปาง
708     ไม่รู้    -1             ลำปาง
...        ...   ...               ...
353978  ไม่รู้  35.0     กรุงเทพมหานคร
353979  ไม่รู้    -1         กาฬสินธุ์
353980  ไม่รู้  25.0     กรุงเทพมหานคร
353981  ไม่รู้  25.0     กรุงเทพมหานคร
353982  ไม่รู้  36.0     กรุงเทพมหานคร

[17655 rows x 3 columns]

In [131]:
this_data_updated['province_of_onset']=='ไม่รู้'

0         False
1         False
2         False
3          True
4         False
          ...
356607     True
356608     True
356609     True
356610     True
356611     True
Name: province_of_onset, Length: 356612, dtype: bool

In [132]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
12,3905885,12/4/2022,11/4/2022,หญิง,28.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
14,3905887,12/4/2022,11/4/2022,ชาย,24.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
22,3905895,12/4/2022,11/4/2022,หญิง,39.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
26,3905899,12/4/2022,11/4/2022,หญิง,26.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [133]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [134]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

        sex   age province_of_onset
704     NaN   NaN             ลำปาง
705     NaN   NaN             ลำปาง
706     NaN   NaN             ลำปาง
707     NaN   NaN             ลำปาง
708     NaN   NaN             ลำปาง
...     ...   ...               ...
353978  NaN  35.0     กรุงเทพมหานคร
353979  NaN   NaN         กาฬสินธุ์
353980  NaN  25.0     กรุงเทพมหานคร
353981  NaN  25.0     กรุงเทพมหานคร
353982  NaN  36.0     กรุงเทพมหานคร

[17655 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [135]:
this_data = data_covid[['sex','age','province_of_onset']]

In [136]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(10647, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10647, dtype: object)
(10720, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10720, dtype: object)
(10883, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10883, dtype: object)
(10916, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10916, dtype: object)
(32982, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 32982, dtype: object)
(33045, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33045, dtype: object)
(33206, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33206, dtype: object)
(33207, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33207, dtype: object)
(33213, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33213, dtype: object)
(33474, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33474, dtype: object)
(33563, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33563, dtype: object)
(33587, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33587, dtype: object)
(33649, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33649, dtype: object)
(56006, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56006, dtype: object)
(56012, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56012, dtype: object)
(56237, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56237, dtype: object)
(56443, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56443, dtype: object)
(56617, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56617, dtype: object)
(56660, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56660, dtype: object)
(56792, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56792, dtype: object)
(56797, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56797, dtype: object)
(210018, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210018, dtype: object)
(210022, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210022, dtype: object)
(210035, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210035, dtype: object)
(210129, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210129, dtype: object)
(210213, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210213, dtype: object)
(210285, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210285, dtype: object)
(210347, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210347, dtype: object)
(210400, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210400, dtype: object)
(210401, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210401, dtype: object)
(210452, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210452, dtype: object)
(210620, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210620, dtype: object)
(210643, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210643, dtype: object)
(210762, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210762, dtype: object)
(210778, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210778, dtype: object)
(231564, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231564, dtype: object)
(231629, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231629, dtype: object)
(231671, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231671, dtype: object)
(231710, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231710, dtype: object)
(231803, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231803, dtype: object)
(231884, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231884, dtype: object)
(232124, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232124, dtype: object)
(232181, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232181, dtype: object)
(232216, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232216, dtype: object)
(232327, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232327, dtype: object)
(250319, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 250319, dtype: object)
(250417, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250417, dtype: object)
(250487, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250487, dtype: object)
(250631, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250631, dtype: object)
(250670, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250670, dtype: object)
(267051, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267051, dtype: object)
(280806, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280806, dtype: object)
(280855, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280855, dtype: object)
(280857, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280857, dtype: object)
(280860, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280860, dtype: object)
(280978, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280978, dtype: object)
(281070, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281070, dtype: object)
(281074, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281074, dtype: object)
(281087, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 281087, dtype: object)
(295128, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295128, dtype: object)
(295212, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295212, dtype: object)
(295330, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 295330, dtype: object)
(295366, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295366, dtype: object)
(295371, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295371, dtype: object)
(309830, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 309830, dtype: object)
(310003, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310003, dtype: object)
(310016, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310016, dtype: object)
(310036, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310036, dtype: object)
(310140, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310140, dtype: object)
(323862, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 323862, dtype: object)
(323879, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323879, dtype: object)
(323984, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323984, dtype: object)
(324027, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 324027, dtype: object)
(337399, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337399, dtype: object)
(337517, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337517, dtype: object)
(337577, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 337577, dtype: object)
(349843, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 349843, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [137]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

10647
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10647, dtype: object
10720
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10720, dtype: object
10883
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10883, dtype: object
10916
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10916, dtype: object
32982
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 32982, dtype: object
33045
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33045, dtype: object
33206
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33206, dtype: object
33207
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33207, dtype: object
33213
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33213, dtype: object
33474
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33474, dtype: object
33563
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33563, dtype: object
33587
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33587, dtype: object
33649
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33649, dtype: object
56006
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56006, dtype: object
56012
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56012, dtype: object
56237
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56237, dtype: object
56443
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56443, dtype: object
56617
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56617, dtype: object
56660
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56660, dtype: object
56792
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56792, dtype: object
56797
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56797, dtype: object
210018
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210018, dtype: object
210022
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210022, dtype: object
210035
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210035, dtype: object
210129
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210129, dtype: object
210213
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210213, dtype: object
210285
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210285, dtype: object
210347
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210347, dtype: object
210400
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210400, dtype: object
210401
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210401, dtype: object
210452
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210452, dtype: object
210620
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210620, dtype: object
210643
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210643, dtype: object
210762
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210762, dtype: object
210778
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210778, dtype: object
231564
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231564, dtype: object
231629
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231629, dtype: object
231671
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231671, dtype: object
231710
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231710, dtype: object
231803
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231803, dtype: object
231884
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231884, dtype: object
232124
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232124, dtype: object
232181
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232181, dtype: object
232216
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232216, dtype: object
232327
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232327, dtype: object
250319
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 250319, dtype: object
250417
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250417, dtype: object
250487
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250487, dtype: object
250631
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250631, dtype: object
250670
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250670, dtype: object
267051
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267051, dtype: object
280806
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280806, dtype: object
280855
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280855, dtype: object
280857
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280857, dtype: object
280860
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280860, dtype: object
280978
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280978, dtype: object
281070
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281070, dtype: object
281074
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281074, dtype: object
281087
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 281087, dtype: object
295128
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295128, dtype: object
295212
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295212, dtype: object
295330
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 295330, dtype: object
295366
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295366, dtype: object
295371
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295371, dtype: object
309830
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 309830, dtype: object
310003
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310003, dtype: object
310016
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310016, dtype: object
310036
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310036, dtype: object
310140
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310140, dtype: object
323862
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 323862, dtype: object
323879
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323879, dtype: object
323984
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323984, dtype: object
324027
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 324027, dtype: object
337399
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337399, dtype: object
337517
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337517, dtype: object
337577
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 337577, dtype: object
349843
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 349843, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [138]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [139]:
data_covid.describe()

                No.
count  3.566120e+05
mean   4.084178e+06
std    1.029452e+05
min    3.905873e+06
25%    3.995026e+06
50%    4.084178e+06
75%    4.173331e+06
max    4.262484e+06

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [155]:
male_age = data_covid[data_covid['sex']=='ชาย']['age']
male_age_numeric = pd.to_numeric(male_age, errors='coerce')
print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย: {male_age_numeric.mean()}')

อายุเฉลี่ย ของ ผู้ป่วยชาย: 39.41913811289394

### ```.isnull()```

In [142]:
data_covid.isnull()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
356607,False,False,False,False,True,True,True,False,False,True,True
356608,False,False,False,False,True,True,True,False,False,True,True
356609,False,False,False,False,True,True,True,False,False,True,True
356610,False,False,False,False,True,True,True,False,False,True,True
356611,False,False,False,False,True,True,True,False,False,True,True

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table

##Homework

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด

คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

หาจำนวนผู้ป่วยที่เป็นคน "คนต่างชาติเดินทางมาจากต่างประเทศ

In [143]:
this_data = data_covid[['sex','age','province_of_onset']]
print(this_data)

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [144]:
female = this_data[(this_data['sex']=='หญิง')&(this_data['sex']=='หญิง')]

In [145]:
female_age_numeric = pd.to_numeric(female['age'], errors='coerce')
mean_age = female_age_numeric.dropna().mean()

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {mean_age}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 41.84962590058987

In [146]:
male = this_data[(this_data['sex']=='ชาย')&(this_data['sex']=='ชาย')]

In [147]:
male_age_numeric = pd.to_numeric(male['age'], errors='coerce')
mean_age = male_age_numeric.dropna().mean()

print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย {mean_age}')

อายุเฉลี่ย ของ ผู้ป่วยชาย 39.41913811289394

In [148]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']
female_KK_age_numeric = pd.to_numeric(female_KK['age'], errors='coerce')

sum_age_kk = 0
N_age_kk = 0
for a in female_KK_age_numeric:
    if a > 0:
        sum_age_kk += a
        N_age_kk += 1

if N_age_kk > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum_age_kk/N_age_kk}')
else:
    print('ไม่มีข้อมูล')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 40.67317497823654

In [150]:
male_KK = male[male['province_of_onset']=='ขอนแก่น']
male_KK_age_numeric = pd.to_numeric(male_KK['age'], errors='coerce')

sum_age_kk = 0
N_age_kk = 0
for a in male_KK_age_numeric:
    if a > 0:
        sum_age_kk += a
        N_age_kk += 1

if N_age_kk > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น {sum_age_kk/N_age_kk}')
else:
    print('ไม่มีข้อมูล')

อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น 37.93367898034133

In [151]:
foreign_travel = data_covid[data_covid['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ']
num_foreign_travel = len(foreign_travel)
print(f'จำนวนผู้ป่วยที่เป็นคนต่างชาติเดินทางมาจากต่างประเทศ: {num_foreign_travel}')

จำนวนผู้ป่วยที่เป็นคนต่างชาติเดินทางมาจากต่างประเทศ: 13

In [152]:
forienge = data_covid[data_covid['nationality']!='Thailand']

In [153]:
forienge.shape

(35610, 11)

In [154]:
data_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

ข้อผิดพลาด TypeError: unsupported operand type(s) for +: 'float' and 'str' เกิดขึ้นเนื่องจากคอลัมน์ 'age' ของข้อมูลผู้ป่วยชายมีค่าที่ไม่ใช่ตัวเลข (เป็นข้อความ) ผสมอยู่ เมื่อพยายามคำนวณค่าเฉลี่ยโดยตรง ฟังก์ชัน mean() จะพยายามรวมค่าเหล่านั้นเข้าด้วยกัน แต่ไม่สามารถรวมตัวเลขกับข้อความได้

การแก้ไขได้ดำเนินการไปแล้วโดยการแปลงคอลัมน์ 'age' ให้เป็นตัวเลขทั้งหมด โดยใช้ pd.to_numeric(male_age, errors='coerce') ซึ่งจะเปลี่ยนค่าที่ไม่สามารถแปลงเป็นตัวเลขได้ให้เป็น NaN (Not a Number) ทำให้ฟังก์ชัน mean() สามารถคำนวณค่าเฉลี่ยจากตัวเลขที่ถูกต้องได้โดยไม่เกิดข้อผิดพลาด